
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - provisioner.k3s.operator
  resources:
  - k3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioner.k3s.operator
  resources:
  - k3s/status
  verbs:
  - get
  - patch
  - update
